env: "local"
storage_path: "./storage.db"
http_server:
  address: "127.0.0.1:50000"
  timeout: 4s
  idle_timeout: 30s
  user: "Shabby8574"
  password: "123"
log:
  slog:
    add_source: true
    level: "debug"
    format: "pretty"
    pretty:
      fields_format: "json"
      emoji: true
      time_layout: "15:04:05"